# Generated by Django 5.2 on 2025-04-06 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='pat_score',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sat_score',
        ),
        migrations.AddField(
            model_name='student',
            name='avg_pat_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='avg_sat_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pat_score', models.FloatField(blank=True, null=True)),
                ('sat_score', models.FloatField(blank=True, null=True)),
                ('marks_obtained', models.FloatField(blank=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
