# Generated by Django 5.1.7 on 2025-04-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='standar_class',
            new_name='standard_class',
        ),
        migrations.AddField(
            model_name='student',
            name='standard',
            field=models.ManyToManyField(to='student.standard'),
        ),
        migrations.AddField(
            model_name='student',
            name='standard_class',
            field=models.ManyToManyField(to='student.classsection'),
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.ManyToManyField(to='student.subject'),
        ),
    ]
