# Generated by Django 5.2 on 2025-04-15 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsuggestion',
            name='student',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentsuggestion',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
