# Generated by Django 5.1.7 on 2025-04-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooladminprofile',
            name='school_id',
            field=models.FileField(blank=True, null=True, upload_to='media/school_ids/'),
        ),
    ]
