# Generated by Django 5.1.7 on 2025-04-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_teacher_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('physics', 'physics'), ('maths', 'maths'), ('chemistry', 'chemistry')], default='Unknown', max_length=10),
        ),
    ]
