# Generated by Django 5.1.7 on 2025-04-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_teacher_gender_alter_teacher_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('p', 'Physics'), ('m', 'Maths'), ('c', 'Chemistry')], default='Unknown', max_length=10),
        ),
    ]
