# Generated by Django 5.2 on 2025-04-09 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='body',
        ),
    ]
